//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMIMobile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_th {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_th() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AMIMobile.AppResources.th", typeof(AppResources_th).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashbord.
        /// </summary>
        internal static string Dashbord {
            get {
                return ResourceManager.GetString("Dashbord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En.
        /// </summary>
        internal static string En {
            get {
                return ResourceManager.GetString("En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เข้าสู่ระบบ.
        /// </summary>
        internal static string SingIn {
            get {
                return ResourceManager.GetString("SingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรอกชื่อผู้ใช้งาน.
        /// </summary>
        internal static string กรอกชื่อผู้ใช้งาน {
            get {
                return ResourceManager.GetString("กรอกชื่อผู้ใช้งาน", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรอกรหัสผ่าน.
        /// </summary>
        internal static string กรอกรหัสผ่าน {
            get {
                return ResourceManager.GetString("กรอกรหัสผ่าน", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรอกรหัสผ่านใหม่.
        /// </summary>
        internal static string กรอกรหัสผ่านใหม่ {
            get {
                return ResourceManager.GetString("กรอกรหัสผ่านใหม่", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรอกอีเมล์.
        /// </summary>
        internal static string กรอกอีเมล์ {
            get {
                return ResourceManager.GetString("กรอกอีเมล์", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การจัดการความปลอดภัย.
        /// </summary>
        internal static string การจัดการความปลอดภัย {
            get {
                return ResourceManager.GetString("การจัดการความปลอดภัย", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การสแกนใบหน้า.
        /// </summary>
        internal static string การสแกนใบหน้า {
            get {
                return ResourceManager.GetString("การสแกนใบหน้า", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกี่ยวกับ.
        /// </summary>
        internal static string เกี่ยวกับ {
            get {
                return ResourceManager.GetString("เกี่ยวกับ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไขรหัสผ่าน.
        /// </summary>
        internal static string แก้ไขรหัสผ่าน {
            get {
                return ResourceManager.GetString("แก้ไขรหัสผ่าน", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค้นหา.
        /// </summary>
        internal static string ค้นหา {
            get {
                return ResourceManager.GetString("ค้นหา", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่ากิโลวัตต์ชั่วโมง.
        /// </summary>
        internal static string ค่ากิโลวัตต์ชั่วโมง {
            get {
                return ResourceManager.GetString("ค่ากิโลวัตต์ชั่วโมง", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่ากิโลวัตต์สูงสุด.
        /// </summary>
        internal static string ค่ากิโลวัตต์สูงสุด {
            get {
                return ResourceManager.GetString("ค่ากิโลวัตต์สูงสุด", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่ากิโลวาร์ชั่วโมง.
        /// </summary>
        internal static string ค่ากิโลวาร์ชั่วโมง {
            get {
                return ResourceManager.GetString("ค่ากิโลวาร์ชั่วโมง", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่ากิโลวาร์สูงสุด.
        /// </summary>
        internal static string ค่ากิโลวาร์สูงสุด {
            get {
                return ResourceManager.GetString("ค่ากิโลวาร์สูงสุด", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าหน่วยสะสม.
        /// </summary>
        internal static string ค่าหน่วยสะสม {
            get {
                return ResourceManager.GetString("ค่าหน่วยสะสม", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จดจำผู้ใช้งาน.
        /// </summary>
        internal static string จดจำผู้ใช้งาน {
            get {
                return ResourceManager.GetString("จดจำผู้ใช้งาน", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ช่วงเวลา.
        /// </summary>
        internal static string ช่วงเวลา {
            get {
                return ResourceManager.GetString("ช่วงเวลา", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้ใช้.
        /// </summary>
        internal static string ชื่อผู้ใช้ {
            get {
                return ResourceManager.GetString("ชื่อผู้ใช้", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดาวน์โหลด.
        /// </summary>
        internal static string ดาวน์โหลด {
            get {
                return ResourceManager.GetString("ดาวน์โหลด", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดำเนินการต่อ.
        /// </summary>
        internal static string ดำเนินการต่อ {
            get {
                return ResourceManager.GetString("ดำเนินการต่อ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตรวจสอบรหัสผ่าน.
        /// </summary>
        internal static string ตรวจสอบรหัสผ่าน {
            get {
                return ResourceManager.GetString("ตรวจสอบรหัสผ่าน", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตั้งค่า.
        /// </summary>
        internal static string ตั้งค่า {
            get {
                return ResourceManager.GetString("ตั้งค่า", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตั้งค่าภาษา.
        /// </summary>
        internal static string ตั้งค่าภาษา {
            get {
                return ResourceManager.GetString("ตั้งค่าภาษา", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไทย.
        /// </summary>
        internal static string ไทย {
            get {
                return ResourceManager.GetString("ไทย", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บัญชีผู้ใช้ไฟฟ้า.
        /// </summary>
        internal static string บัญชีผู้ใช้ไฟฟ้า {
            get {
                return ResourceManager.GetString("บัญชีผู้ใช้ไฟฟ้า", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บัญชีผู้ใช้ไฟฟ้า:.
        /// </summary>
        internal static string บัญชีผู้ใช้ไฟฟ้า_ {
            get {
                return ResourceManager.GetString("บัญชีผู้ใช้ไฟฟ้า:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกการเข้าใช้งาน.
        /// </summary>
        internal static string บันทึกการเข้าใช้งาน {
            get {
                return ResourceManager.GetString("บันทึกการเข้าใช้งาน", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เบอร์โทรศัพท์.
        /// </summary>
        internal static string เบอร์โทรศัพท์ {
            get {
                return ResourceManager.GetString("เบอร์โทรศัพท์", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบอ่านหน่วย.
        /// </summary>
        internal static string ใบอ่านหน่วย {
            get {
                return ResourceManager.GetString("ใบอ่านหน่วย", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เปลี่ยนรหัสผ่าน.
        /// </summary>
        internal static string เปลี่ยนรหัสผ่าน {
            get {
                return ResourceManager.GetString("เปลี่ยนรหัสผ่าน", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้ใช้งาน.
        /// </summary>
        internal static string ผู้ใช้งาน {
            get {
                return ResourceManager.GetString("ผู้ใช้งาน", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ภาษาไทย.
        /// </summary>
        internal static string ภาษาไทย {
            get {
                return ResourceManager.GetString("ภาษาไทย", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ภาษาอังกฤษ.
        /// </summary>
        internal static string ภาษาอังกฤษ {
            get {
                return ResourceManager.GetString("ภาษาอังกฤษ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บัญชีผู้ใช้.
        /// </summary>
        internal static string เมนูบัญชีผู้ใช้ไฟฟ้า {
            get {
                return ResourceManager.GetString("เมนูบัญชีผู้ใช้ไฟฟ้า", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยัน.
        /// </summary>
        internal static string ยืนยัน {
            get {
                return ResourceManager.GetString("ยืนยัน", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันรหัสผ่านใหม่.
        /// </summary>
        internal static string ยืนยันรหัสผ่านใหม่ {
            get {
                return ResourceManager.GetString("ยืนยันรหัสผ่านใหม่", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่าน.
        /// </summary>
        internal static string รหัสผ่าน {
            get {
                return ResourceManager.GetString("รหัสผ่าน", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่านปัจจุบัน.
        /// </summary>
        internal static string รหัสผ่านปัจจุบัน {
            get {
                return ResourceManager.GetString("รหัสผ่านปัจจุบัน", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รอบบิลสิงหาคม 2565.
        /// </summary>
        internal static string รอบบิล {
            get {
                return ResourceManager.GetString("รอบบิล", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายงาน:.
        /// </summary>
        internal static string รายงาน_ {
            get {
                return ResourceManager.GetString("รายงาน:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพื่อรักษาความปลอดภัยบัญชีของคุณ กรุณายืนยันตัวตนโดยการใส่รหัสผ่าน.
        /// </summary>
        internal static string รายละเอียดตรวจสอบรหัสผ่าน {
            get {
                return ResourceManager.GetString("รายละเอียดตรวจสอบรหัสผ่าน", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกชื่อผู้ใช้ และอีเมล์เพื่อตั้งค่ารหัสผ่านใหม่.
        /// </summary>
        internal static string รายละเอียดลืมรหัสผ่าน {
            get {
                return ResourceManager.GetString("รายละเอียดลืมรหัสผ่าน", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลงชื่อเข้าใช้.
        /// </summary>
        internal static string ลงชื่อเข้าใช้ {
            get {
                return ResourceManager.GetString("ลงชื่อเข้าใช้", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลืมรหัสผ่าน.
        /// </summary>
        internal static string ลืมรหัสผ่าน {
            get {
                return ResourceManager.GetString("ลืมรหัสผ่าน", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกช่วงเวลา.
        /// </summary>
        internal static string เลือกช่วงเวลา {
            get {
                return ResourceManager.GetString("เลือกช่วงเวลา", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกรายงาน.
        /// </summary>
        internal static string เลือกรายงาน {
            get {
                return ResourceManager.GetString("เลือกรายงาน", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกวันที่.
        /// </summary>
        internal static string เลือกวันที่ {
            get {
                return ResourceManager.GetString("เลือกวันที่", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกหมายเลขมิเตอร์.
        /// </summary>
        internal static string เลือกหมายเลขมิเตอร์ {
            get {
                return ResourceManager.GetString("เลือกหมายเลขมิเตอร์", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่.
        /// </summary>
        internal static string วันที่ {
            get {
                return ResourceManager.GetString("วันที่", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่ง.
        /// </summary>
        internal static string ส่ง {
            get {
                return ResourceManager.GetString("ส่ง", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขมิเตอร์.
        /// </summary>
        internal static string หมายเลขมิเตอร์ {
            get {
                return ResourceManager.GetString("หมายเลขมิเตอร์", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขมิเตอร์:.
        /// </summary>
        internal static string หมายเลขมิเตอร์_ {
            get {
                return ResourceManager.GetString("หมายเลขมิเตอร์:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อย่างน้อย 8 ตัวอักษรประกอบไปด้วยอักษรตัวเล็ก ตัวใหญ่ตัวเลข และอักขระพิเศษ.
        /// </summary>
        internal static string หมายเหตุเปลี่ยนรหัสผ่าน {
            get {
                return ResourceManager.GetString("หมายเหตุเปลี่ยนรหัสผ่าน", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โหลดโปรไฟล์.
        /// </summary>
        internal static string โหลดโปรไฟล์ {
            get {
                return ResourceManager.GetString("โหลดโปรไฟล์", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ออกจากระบบ.
        /// </summary>
        internal static string ออกจากระบบ {
            get {
                return ResourceManager.GetString("ออกจากระบบ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมล์.
        /// </summary>
        internal static string อีเมล์ {
            get {
                return ResourceManager.GetString("อีเมล์", resourceCulture);
            }
        }
    }
}
