//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMIMobile
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_en
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_en()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AMIMobile.AppResources.en", typeof(AppResources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dashbord.
        /// </summary>
        internal static string Dashbord
        {
            get
            {
                return ResourceManager.GetString("Dashbord", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to En.
        /// </summary>
        internal static string En
        {
            get
            {
                return ResourceManager.GetString("En", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter Username.
        /// </summary>
        internal static string กรอกชื่อผู้ใช้งาน
        {
            get
            {
                return ResourceManager.GetString("กรอกชื่อผู้ใช้งาน", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        internal static string กรอกรหัสผ่าน
        {
            get
            {
                return ResourceManager.GetString("กรอกรหัสผ่าน", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter Username.
        /// </summary>
        internal static string กรอกอีเมล์
        {
            get
            {
                return ResourceManager.GetString("กรอกอีเมล์", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string การจัดการความปลอดภัย
        {
            get
            {
                return ResourceManager.GetString("การจัดการความปลอดภัย", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Face Scanning.
        /// </summary>
        internal static string การสแกนใบหน้า
        {
            get
            {
                return ResourceManager.GetString("การสแกนใบหน้า", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fingerprint Scanning.
        /// </summary>
        internal static string การสแกนลายนิ้วมือ
        {
            get
            {
                return ResourceManager.GetString("การสแกนลายนิ้วมือ", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scanning.
        /// </summary>
        internal static string การสแกนลายนิ้วมือ___ใบหน้า
        {
            get
            {
                return ResourceManager.GetString("การสแกนลายนิ้วมือ / ใบหน้า", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string เกี่ยวกับ
        {
            get
            {
                return ResourceManager.GetString("เกี่ยวกับ", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit Password.
        /// </summary>
        internal static string แก้ไขรหัสผ่าน
        {
            get
            {
                return ResourceManager.GetString("แก้ไขรหัสผ่าน", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sing In.
        /// </summary>
        internal static string เข้าสู่ระบบ
        {
            get
            {
                return ResourceManager.GetString("เข้าสู่ระบบ", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ค้นหา
        {
            get
            {
                return ResourceManager.GetString("ค้นหา", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kilowatt Hour.
        /// </summary>
        internal static string ค่ากิโลวัตต์ชั่วโมง
        {
            get
            {
                return ResourceManager.GetString("ค่ากิโลวัตต์ชั่วโมง", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum Kilowatt.
        /// </summary>
        internal static string ค่ากิโลวัตต์สูงสุด
        {
            get
            {
                return ResourceManager.GetString("ค่ากิโลวัตต์สูงสุด", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kilovar Hour.
        /// </summary>
        internal static string ค่ากิโลวาร์ชั่วโมง
        {
            get
            {
                return ResourceManager.GetString("ค่ากิโลวาร์ชั่วโมง", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum Kilovar.
        /// </summary>
        internal static string ค่ากิโลวาร์สูงสุด
        {
            get
            {
                return ResourceManager.GetString("ค่ากิโลวาร์สูงสุด", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cumulative Unit.
        /// </summary>
        internal static string ค่าหน่วยสะสม
        {
            get
            {
                return ResourceManager.GetString("ค่าหน่วยสะสม", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remember.
        /// </summary>
        internal static string จดจำผู้ใช้งาน
        {
            get
            {
                return ResourceManager.GetString("จดจำผู้ใช้งาน", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        internal static string ช่วงเวลา
        {
            get
            {
                return ResourceManager.GetString("ช่วงเวลา:", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string ชื่อผู้ใช้
        {
            get
            {
                return ResourceManager.GetString("ชื่อผู้ใช้", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string ดาวน์โหลด
        {
            get
            {
                return ResourceManager.GetString("ดาวน์โหลด", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string ดำเนินการต่อ
        {
            get
            {
                return ResourceManager.GetString("ดำเนินการต่อ", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Check Password.
        /// </summary>
        internal static string ตรวจสอบรหัสผ่าน
        {
            get
            {
                return ResourceManager.GetString("ตรวจสอบรหัสผ่าน", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string ตั้งค่า
        {
            get
            {
                return ResourceManager.GetString("ตั้งค่า", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string ตั้งค่าภาษา
        {
            get
            {
                return ResourceManager.GetString("ตั้งค่าภาษา", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ไทย.
        /// </summary>
        internal static string ไทย
        {
            get
            {
                return ResourceManager.GetString("ไทย", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customer Account.
        /// </summary>
        internal static string บัญชีผู้ใช้ไฟฟ้า
        {
            get
            {
                return ResourceManager.GetString("บัญชีผู้ใช้ไฟฟ้า", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customer Account:.
        /// </summary>
        internal static string บัญชีผู้ใช้ไฟฟ้า_
        {
            get
            {
                return ResourceManager.GetString("บัญชีผู้ใช้ไฟฟ้า:", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access Log.
        /// </summary>
        internal static string บันทึกการเข้าใช้งาน
        {
            get
            {
                return ResourceManager.GetString("บันทึกการเข้าใช้งาน", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tel..
        /// </summary>
        internal static string เบอร์โทรศัพท์
        {
            get
            {
                return ResourceManager.GetString("เบอร์โทรศัพท์", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Biling.
        /// </summary>
        internal static string ใบอ่านหน่วย
        {
            get
            {
                return ResourceManager.GetString("ใบอ่านหน่วย", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string เปลี่ยนรหัสผ่าน
        {
            get
            {
                return ResourceManager.GetString("เปลี่ยนรหัสผ่าน", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string ผู้ใช้งาน
        {
            get
            {
                return ResourceManager.GetString("ผู้ใช้งาน", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thai.
        /// </summary>
        internal static string ภาษาไทย
        {
            get
            {
                return ResourceManager.GetString("ภาษาไทย", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string ภาษาอังกฤษ
        {
            get
            {
                return ResourceManager.GetString("ภาษาอังกฤษ", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cust Acct..
        /// </summary>
        internal static string เมนูบัญชีผู้ใช้ไฟฟ้า
        {
            get
            {
                return ResourceManager.GetString("เมนูบัญชีผู้ใช้ไฟฟ้า", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string ยืนยัน
        {
            get
            {
                return ResourceManager.GetString("ยืนยัน", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        internal static string ยืนยันรหัสผ่านใหม่
        {
            get
            {
                return ResourceManager.GetString("ยืนยันรหัสผ่านใหม่", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string รหัสผ่าน
        {
            get
            {
                return ResourceManager.GetString("รหัสผ่าน", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string รหัสผ่านปัจจุบัน
        {
            get
            {
                return ResourceManager.GetString("รหัสผ่านปัจจุบัน", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Billing August 2022.
        /// </summary>
        internal static string รอบบิล
        {
            get
            {
                return ResourceManager.GetString("รอบบิล", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Report:.
        /// </summary>
        internal static string รายงาน_
        {
            get
            {
                return ResourceManager.GetString("รายงาน:", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please verify your identity by entering your 
        ///password to secure your account..
        /// </summary>
        internal static string รายละเอียดตรวจสอบรหัสผ่าน
        {
            get
            {
                return ResourceManager.GetString("รายละเอียดตรวจสอบรหัสผ่าน", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter your username and email to reset your password..
        /// </summary>
        internal static string รายละเอียดลืมรหัสผ่าน
        {
            get
            {
                return ResourceManager.GetString("รายละเอียดลืมรหัสผ่าน", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string ลงชื่อเข้าใช้
        {
            get
            {
                return ResourceManager.GetString("ลงชื่อเข้าใช้", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string ลืมรหัสผ่าน
        {
            get
            {
                return ResourceManager.GetString("ลืมรหัสผ่าน", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to เลือกช่วงเวลา.
        /// </summary>
        internal static string เลือกช่วงเวลา
        {
            get
            {
                return ResourceManager.GetString("เลือกช่วงเวลา", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to เลือกรายงาน.
        /// </summary>
        internal static string เลือกรายงาน
        {
            get
            {
                return ResourceManager.GetString("เลือกรายงาน", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to เลือกวันที่.
        /// </summary>
        internal static string เลือกวันที่
        {
            get
            {
                return ResourceManager.GetString("เลือกวันที่", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to เลือกหมายเลขมิเตอร์.
        /// </summary>
        internal static string เลือกหมายเลขมิเตอร์
        {
            get
            {
                return ResourceManager.GetString("เลือกหมายเลขมิเตอร์", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string วันที่
        {
            get
            {
                return ResourceManager.GetString("วันที่:", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string ส่ง
        {
            get
            {
                return ResourceManager.GetString("ส่ง", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Meter No..
        /// </summary>
        internal static string หมายเลขมิเตอร์
        {
            get
            {
                return ResourceManager.GetString("หมายเลขมิเตอร์", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Meter No:.
        /// </summary>
        internal static string หมายเลขมิเตอร์_
        {
            get
            {
                return ResourceManager.GetString("หมายเลขมิเตอร์:", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to At least 8 characters, including uppercase and lowercase 
        ///letters numbers and special characters.
        /// </summary>
        internal static string หมายเหตุเปลี่ยนรหัสผ่าน
        {
            get
            {
                return ResourceManager.GetString("หมายเหตุเปลี่ยนรหัสผ่าน", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Load Profile.
        /// </summary>
        internal static string โหลดโปรไฟล์
        {
            get
            {
                return ResourceManager.GetString("โหลดโปรไฟล์", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string ออกจากระบบ
        {
            get
            {
                return ResourceManager.GetString("ออกจากระบบ", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string อีเมล์
        {
            get
            {
                return ResourceManager.GetString("อีเมล์", resourceCulture);
            }
        }
    }
}
